# Fix for "[oh-my-zsh] Insecure completion-dependent directories detected"
# https://stackoverflow.com/questions/61433167/zsh-detects-insecure-completion-dependent-directories
ZSH_DISABLE_COMPFIX=true

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git command-not-found docker mvn bundler gem rails yarn notify)

source $ZSH/oh-my-zsh.sh

# ASDF Java
# TODO: Move to tag-asdf or separate asdf config file?
. ~/.asdf/plugins/java/set-java-home.zsh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# zsh-notify https://github.com/marzocchi/zsh-notify
zstyle ':notify:*' error-sound "Glass"
zstyle ':notify:*' success-sound "default"

# Ruby on Rails
# - rss requires a key and certificate to be setup
alias rss="rails server -b 'ssl://localhost:3000?key=server.key&cert=server.crt'"

# Set DEPENDENCIES_NEXT environment variable for use with bootboot's "next"
# gemset
alias dn="DEPENDENCIES_NEXT=1"

# Homebrew
# Determine Homebrew prefix
arch="$(uname -m)"
if [ "$arch" = "arm64" ]; then
  HOMEBREW_PREFIX="/opt/homebrew"
else
  HOMEBREW_PREFIX="/usr/local"
fi

eval "$($HOMEBREW_PREFIX/bin/brew shellenv)"

# ASDF installed via Homebrew
source "$HOMEBREW_PREFIX/opt/asdf/libexec/asdf.sh"

# ls to eza alias
alias ls="eza"

export ASDF_NODEJS_LEGACY_FILE_DYNAMIC_STRATEGY=latest_available

# Local config
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local

export PATH="$HOME/.bin:$HOME/.local/bin:$PATH"

#
# Starship prompt
#
eval "$(starship init zsh)"

#
# zsh-users tools MUST BE AT THE END OF THE FILE
#

# See note about iterm2 colors here:
#   https://github.com/zsh-users/zsh-autosuggestions#suggestion-highlight-style
source "$HOMEBREW_PREFIX/share/zsh-autosuggestions/zsh-autosuggestions.zsh"
bindkey '^[[Z' autosuggest-accept

# zsh-users/zsh-syntax-highlighting
source "$HOMEBREW_PREFIX/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"

# zsh-users/zsh-substring-search
source "$HOMEBREW_PREFIX/share/zsh-history-substring-search/zsh-history-substring-search.zsh"
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down
